name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions
on:
  workflow_call:

jobs:
  run-shared-workflow:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
        with:
          repository: JuozasVainauskas/gh-shared-workflows-test
      - name: Run hello-world.sh
        run: ./scripts/hello-world.sh
